trigger:  
  - main
variables:
  buildConfiguration: 'Release'
  vmImageName: 'windows-latest'
  functionAppName: 'func-azap-app-common'
  serviceConnectionDev: 'devops_2_PRH-DE-BI-DEV'  
  serviceConnectionProd: 'AZAP-PRH-DE-BI-SP'  
  functionName: 'func-azap-app-common'
  projectName: 'func-azap-app-common'
  deployOnProd: true
stages: 
  - stage: Build 
   
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build func-azap-app-common
        pool:
          vmImage:  $(vmImageName)
        steps:
          - task: DotNetCoreCLI@2
            displayName: Restore
            inputs:
              command: 'restore'
              projects:  '$(functionName).csproj'
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: 'build'
              projects: '$(functionName).csproj'
              arguments: --configuration $(buildConfiguration)        
          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: 'publish'
              publishWebProjects: false
              projects: '$(functionName).csproj'
              arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'  
              zipAfterPublish: True                         
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'             
  - stage: DeployDev
    displayName: 'Deploy func-azap-app-common-dev'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy func-azap-app-common-dev
        environment: Development
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy Azure Function'
                  inputs:
                    azureSubscription: '$(serviceConnectionDev)'
                    appType: functionApp
                    WebAppName: '$(functionAppName)-dev'                   
                    package: '$(Pipeline.Workspace)/drop/s.zip'                   
                    enableCustomDeployment: true
                    RemoveAdditionalFilesFlag: true
  - stage: DeployProd
    displayName: 'Deploy func-azap-app-common-prod'
    dependsOn: DeployDev
    condition: and(succeeded(), eq(variables.deployOnProd, 'true'))
    jobs:
      - deployment: Deploy
        displayName: Deploy func-azap-app-common-prod
        environment: Production
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: 'Deploy Azure Function'
                  inputs:
                    azureSubscription: '$(serviceConnectionProd)'
                    appType: functionApp
                    WebAppName: '$(functionAppName)-prod'                   
                    package: '$(Pipeline.Workspace)/drop/s.zip'                   
                    enableCustomDeployment: true
                    RemoveAdditionalFilesFlag: true