name: Deploy DotNet project to Azure Function App

on:
  # push:
  #   branches: ["main"]

  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'func-azap-app-github'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    permissions:
          id-token: write # Required for OIDC
          contents: read # Required for actions/checkout
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: 'Log in to Azure with AZ CLI'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.TECHDATA_CLIENTID }} # Required to log in with OIDC
        tenant-id: ${{ vars.BERTELSMANN_TENANTID }} # Required to log in with OIDC
        subscription-id: ${{ vars.TECHDATA_SUBSCRIPTIONID_DEV }} # Required to log in with OIDC

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh # For Linux, use bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: deploy-to-function-app
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}-dev
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy-prod:
    runs-on: windows-latest
    needs: build-and-deploy
    permissions:
      id-token: write
    environment: prod
    steps:
      - name: 'Log in to Azure (prod)'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TECHDATA_CLIENTID }}
          tenant-id: ${{ vars.BERTELSMANN_TENANTID }}
          subscription-id: ${{ vars.TECHDATA_SUBSCRIPTIONID_PROD }}
      - name: 'Deploy to Production'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}-prod
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
